export {default as Navbar} from './Navbar/Navbar.jsx'
export {default as Header} from './Header/Header.jsx'
export {default as Brand} from './Brand/Brand.jsx'
export {default as WhatGPT3} from './What GPT3/WhatGPT3.jsx'
export {default as Features} from './Features/Features.jsx'
export {default as Possibility} from './Possibility/Possibility.jsx'
export {default as Cta} from './CTA/Cta.jsx'
export {default as Blog} from './Blog/Blog.jsx'
export {default as Footer} from './Footer/Footer.jsx'